# Generated by Django 3.0.2 on 2020-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='Img',
            field=models.ImageField(default='src', upload_to='images/'),
        ),
    ]
