# Generated by Django 3.0.2 on 2020-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart01', '0002_shopproduct_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='Img',
            field=models.ImageField(default='True', upload_to='images/'),
        ),
    ]
