# Generated by Django 3.0.2 on 2020-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart01', '0003_auto_20200225_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user name', max_length=120)),
                ('password', models.CharField(default='password', max_length=50)),
            ],
        ),
    ]
